bboard/urls.py
from django.urls import path
from .views import index, by_rubric, BbCreateView

app_name = 'bboard'

urlpatterns = [
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('', index, name='index'),

]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include
from bboard.views import index

urlpatterns = [
    path('bboard/', include('bboard.urls')),
    path('admin/', admin.site.urls),

]

bboard/models.py
from django.db import models


class Bb(models.Model):
    # Если не задано значение по умолчанию, то появится значение -----, его можно поменять (None, 'Укажите тип')

    # Перечисление со строковыми(целочисленными models.IntegerChoices) значениями choices=Kinds.choices,
    # default=Kinds.SELL. если тип данных - произвольный, то class ChoicesClass(float, models.Choices)
    class Kinds(models.TextChoices):
        """
        Наследник от enum
        """
        SELL = 's', 'Куплю'
        BUY = 'b', 'Продам'
        EXCHANGE = 'c', 'Обменяю'
        RENT = 'r', 'Напрокат'
        __empty__ = 'Выберите тип публикумого объявления'

    class Measurements(float, models.Choices):
        METERS = 1.0, 'Метры'
        FEET = 0.3048, 'Футы'
        YARDS = 0.9144, 'Ярды'



    KINDS = [
        ('Купля-продажа', (
            ('b', 'Куплю'),
            ('s', 'Продам'),
        )),
        ('Обмен', (
            ('c', 'Обменяю'),
        ))
    ]

    title = models.CharField(max_length=50, verbose_name='Товар')
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')
    # Если доступ к связной модели не требуется, то можно сэкономить ресурс и добавить related_name=+
    # default -> <имя_модели>_set
    rubric = models.ForeignKey(to='Rubric', on_delete=models.PROTECT, verbose_name='Рубрика',
                               related_name='entries', null=True, limit_choices_to={'show': True})
    kind = models.CharField(max_length=1, choices=KINDS, default='s')

    # measurement = models.FloatField(choices=Measurements.choices)
    # db_constraint=True - сохраняет ссылочную целлостность на уровне базы данных, а не только в Django при False
    def __str__(self):
        return f'{self.title}'



    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published', 'title']


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')
    show = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return '/bboard/%s/' % self.pk

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'
        ordering = ['name']
        get_latest_by = 'published'


class Spare(models.Model):
    name = models.CharField(max_length=30)


class Machine(models.Model):
    name = models.CharField(max_length=100)
    spares = models.ManyToManyField(Spare)

bboard/forms.py
from django.forms import ModelForm

from .models import Bb


class BbForm(ModelForm):
    class Meta:
        model = Bb
        fields = ('title', 'content', 'rubric', 'price',)



bboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse_lazy as _
from django.views.generic import CreateView

from .forms import BbForm
from .models import Bb, Rubric


def index(request):
    bbs = Bb.objects.all()
    rubrics = Rubric.objects.all()
    context = {
        'bbs': bbs,
        'rubrics': rubrics,
    }

    return render(request, 'bboard/index.html', context=context)


def by_rubric(request, rubric_id: int):
    bbs = Bb.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(pk=rubric_id)
    context = {
        'bbs': bbs,
        'rubrics': rubrics,
        'current_rubric': current_rubric,
    }

    return render(request, 'bboard/by_rubric.html', context=context)


class BbCreateView(CreateView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    success_url = _('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context

# def index(request):
#     s = 'Список объявлений\r\n\r\n\r\n'
#     for bb in Bb.objects.all().order_by('-published'):
#         s += bb.title + '\r\n' + bb.content + '\r\n'
#
#     return HttpResponse(s, content_type='text/plain; charset=utf-8')

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}
    {{ current_rubric.name }}
{% endblock %}

{% block content %}
    <h2>Рубрика : {{ current_rubric.name }}</h2>

    {% for bb in bbs %}
        <div>
            <h2> {{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}
{% endblock %}

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}

{% block title %}
    Добавление объявления
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}
{% block content %}
{% for bb in bbs %}
    <div>
        <h2>{{ bb.title }}</h2>
        <p> {{ bb.content }}</p>
        {% if bb.rubric %}
            <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
            <p> {{ bb.published|date:"d.m.Y H:i:s" }}</p>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}

bboard/templates/layout/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}Главная{% endblock %} :: Доска объявлений</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bboard/style.css' %}">
</head>
<body>
<header>
    <h1>Объявления</h1>
</header>
<nav>
    <a href="{% url 'bboard:index' %}">Главная</a>
    <a href="{% url 'bboard:add' %}">Добавить статью</a>
    {% for rubric in rubrics %}
        <a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a>
    {% endfor %}
</nav>

<section>
    {% block content %}
    {% endblock %}
</section>

</body>
</html>